# 🧠 ETL Pipeline on Fitness Data

## 🚀 Inspiration  
Understanding **lifestyle factors** that contribute to **obesity** is key to enabling early interventions, crafting personalized health recommendations, and powering **machine learning** solutions in healthcare. This dataset offers a comprehensive view into daily habits and their link to obesity levels.

---

## 📊 Column Descriptions

| Feature                        | Description |
|-------------------------------|-------------|
| **Gender**                    | Biological sex of the individual (Male/Female). |
| **Age**                       | Age in years. |
| **Height**                    | Height in meters (m). |
| **Weight**                    | Weight in kilograms (kg). |
| **family_history_with_overweight** | Family history of being overweight (Yes/No). |
| **FAVC**                      | Frequent consumption of high-calorie food (Yes/No). |
| **FCVC**                      | Frequency of vegetable consumption (Scale: 1 to 3). |
| **NCP**                       | Number of main meals per day. |
| **CAEC**                      | Snacking frequency between meals (Never, Sometimes, Frequently, Always). |
| **SMOKE**                     | Smoking habit (Yes/No). |
| **CH2O**                      | Daily water intake (Scale: 1 to 3). |
| **SCC**                       | Whether the person monitors calorie intake (Yes/No). |
| **FAF**                       | Frequency of physical activity (Scale: 0 to 3). |
| **TUE**                       | Time spent using technology daily (Scale: 0 to 3). |
| **CALC**                      | Alcohol consumption frequency (Never, Sometimes, Frequently, Always). |
| **MTRANS**                    | Primary mode of transportation (Automobile, Bike, Motorbike, Public Transport, Walking). |
| **NObeyesdad**                | Obesity level classification:<br> _Insufficient Weight, Normal Weight, Overweight Level I/II, Obesity Type I/II/III_. |

---

## 💡 Use Case  
This dataset empowers:
- 📉 Predictive Modeling for Obesity Risk  
- 💬 Personalized Health & Wellness Insights  
- 📈 Data-Driven Public Health Decisions  

Ready to dive into the data and transform insights into impact? 💥


### Library Importation

In [193]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import Mere_functions as my

import warnings
warnings.filterwarnings("ignore")

## Data Extraction

In [194]:
data = my.read_data("""ObesityDataSet_raw_and_data_sinthetic.csv""")

In [195]:
data

Id    Gender  Age  Height  Weight  \
0         Person_01    Female   21    1.62   64.00   
1         Person_02    Female   21    1.52   56.00   
2         Person_03      Male   23    1.80   77.00   
3         Person_04      Male   27    1.80   87.00   
4         Person_05      Male   22    1.78   89.80   
...             ...       ...  ...     ...     ...   
10305  Person_10306      Male   26    1.84   96.19   
10306  Person_10307      Male   23    1.82   93.09   
10307  Person_10308      Male   23    1.72   85.31   
10308  Person_10309      Male   23    1.79   90.00   
10309  Person_10310  LGBTQAB+   25    1.70   80.75   

      family_history_with_overweight FAVC  FCVC   NCP       CAEC SMOKE  CH2O  \
0                                yes   no  2.00  3.00  Sometimes    no  2.00   
1                                yes   no  3.00  3.00  Sometimes   yes  3.00   
2                                yes   no  2.00  3.00  Sometimes    no  2.00   
3                                 no   no  3.00  3.00  Sometimes    no  2.00   
4                                 no   no  2.00  1.00  Sometimes    no  2.00   
...                              ...  ...   ...   ...        ...   ...   ...   
10305                            yes  yes  1.32  2.28  Sometimes    no  2.00   
10306                            yes  yes  1.88  1.24  Sometimes    no  2.00   
10307                            yes  yes  2.95  3.00  Sometimes    no  2.97   
10308                            yes  yes  2.07  3.00  Sometimes    no  1.08   
10309                            yes  yes  2.55  3.00  Sometimes    no  2.27   

       SCC   FAF    TUE        CALC                 MTRANS  \
0       no  0.00  1.000          no  Public_Transportation   
1      yes  3.00  0.000   Sometimes  Public_Transportation   
2       no  2.00  1.000  Frequently  Public_Transportation   
3       no  2.00  0.000  Frequently                Walking   
4       no  0.00  0.000   Sometimes  Public_Transportation   
...    ...   ...    ...         ...                    ...   
10305   no  1.81  1.940   Sometimes  Public_Transportation   
10306   no  0.00  1.541   Sometimes  Public_Transportation   
10307   no  0.00  0.947   Sometimes  Public_Transportation   
10308   no  0.00  1.922   Sometimes  Public_Transportation   
10309   no  0.50  1.000  Frequently  Public_Transportation   

                NObeyesdad  
0            Normal_Weight  
1            Normal_Weight  
2            Normal_Weight  
3       Overweight_Level_I  
4      Overweight_Level_II  
...                    ...  
10305  Overweight_Level_II  
10306  Overweight_Level_II  
10307  Overweight_Level_II  
10308  Overweight_Level_II  
10309  Overweight_Level_II  

[10310 rows x 18 columns]

### Initial Exploration

In [196]:
data.columns

Index(['Id', 'Gender', 'Age', 'Height', 'Weight',
       'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC',
       'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [197]:
my.rowcols(data)

The Numbers of Rows in this Data are 10310
The Numbers of Columns in this Data are 18


In [198]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10310 entries, 0 to 10309
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Id                              10310 non-null  object 
 1   Gender                          10310 non-null  object 
 2   Age                             10310 non-null  int64  
 3   Height                          10310 non-null  float64
 4   Weight                          10310 non-null  float64
 5   family_history_with_overweight  10310 non-null  object 
 6   FAVC                            10310 non-null  object 
 7   FCVC                            10278 non-null  float64
 8   NCP                             10310 non-null  float64
 9   CAEC                            10024 non-null  object 
 10  SMOKE                           10310 non-null  object 
 11  CH2O                            10187 non-null  float64
 12  SCC                             

In [199]:
data.head()

Id  Gender  Age  Height  Weight family_history_with_overweight FAVC  \
0  Person_01  Female   21    1.62    64.0                            yes   no   
1  Person_02  Female   21    1.52    56.0                            yes   no   
2  Person_03    Male   23    1.80    77.0                            yes   no   
3  Person_04    Male   27    1.80    87.0                             no   no   
4  Person_05    Male   22    1.78    89.8                             no   no   

   FCVC  NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0   2.0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1   3.0  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2   2.0  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3   3.0  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4   2.0  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [200]:
data['Id'].unique()

array(['Person_01', 'Person_02', 'Person_03', ..., 'Person_10308',
       'Person_10309', 'Person_10310'], dtype=object)

It is the UNIQUE identifier of the table we will make it index for further.


In [201]:
data['Gender'].unique()

array(['Female', 'Male', 'LGBTQAB+', 'male'], dtype=object)

We have 3 genders male , female and LGBTQAB+ and we have 2 Spelling of Male so we have to tranform this column in the ETL.

In [202]:
data['FAVC'].unique()

array(['no', 'yes', 'Nope'], dtype=object)

In FAVC Column We have only 2 Possible values Yes and No as No and Nope are same so it also requires Transformation in the ETL Part.

In [203]:
data['family_history_with_overweight'].unique()

array(['yes', 'no', 'Nope'], dtype=object)

In Family History Column We have only 2 Possible values Yes and No as No and Nope are same so it also requires Transformation in the ETL Part.

In [204]:
data['FCVC'].unique()

array([2.  , 3.  , 1.  , 2.45, 2.88, 2.01, 2.6 , 2.59, 2.39, 1.12, 2.03,
       2.66, 2.89, 2.71, 2.75, 1.49, 2.21, 2.06, 2.31, 2.82, 2.05, 2.77,
       2.74, 2.57, 2.52, 2.97, 1.08, 1.27, 1.34, 2.96, 2.73, 2.84, 2.44,
       2.43, 2.93, 2.02, 1.03, 1.59, 1.21, 1.52, 2.7 , 2.36, 2.14, 2.56,
       2.34, 1.81, 2.72, 1.13, 1.76, 2.98, 2.2 , 2.53, 2.24, 2.65, 2.9 ,
       2.48, 2.95, 2.78, 1.01, 2.94, 1.89, 1.95, 2.28, 2.37, 2.32, 2.62,
       1.05, 2.76, 2.07, 2.69, 2.79, 2.67, 1.14, 2.19, 2.92, 2.85, 2.58,
       2.51, 2.91, 2.61, 2.63, 2.49, 1.69, 1.6 , 1.2 , 2.87, 1.64, 1.57,
       1.04, 1.65, 2.12, 2.86, 2.42, 1.79, 1.3 , 1.87, 1.45, 2.11, 1.94,
       1.75, 2.54, 2.4 , 1.62, 1.28, 1.73, 2.3 , 2.29, 1.91, 1.83, 2.22,
       2.8 , 2.09, 1.9 , 1.98, 1.06, 1.99, 2.25, 1.31, 1.32, 2.81, 2.46,
       2.64, 2.1 , 1.97, 2.18, 2.15, 1.77, 1.19, 2.99, 2.27, 2.16, 1.84,
       1.88, 2.55, 1.93, 1.96, 2.13, 2.68, 2.26, 2.35, 1.72, 1.1 , 2.41,
       1.78, 2.33, 2.04, 2.5 , 2.08, 1.36, 1.71, 1.

In FCVC Column we have a rating of how frequent vegetable consumption is on the scale of 1 to 3 and it is a continous column so we need to make it categorical for further use.

In [205]:
data['NCP'].unique()

array([3.  , 1.  , 4.  , 3.29, 1.73, 2.58, 1.6 , 1.74, 1.11, 2.08, 1.89,
       2.86, 3.77, 3.69, 3.16, 1.08, 3.56, 3.89, 3.24, 3.9 , 3.11, 3.59,
       2.06, 2.  , 3.82, 3.09, 3.75, 3.57, 3.73, 3.52, 1.26, 1.27, 3.3 ,
       3.65, 3.54, 1.72, 2.88, 3.63, 1.47, 3.17, 3.49, 2.99, 2.13, 3.91,
       3.7 , 3.18, 3.8 , 1.63, 3.76, 3.37, 2.71, 3.34, 2.22, 2.89, 3.5 ,
       3.19, 1.7 , 2.81, 1.61, 1.88, 2.33, 1.99, 2.97, 3.72, 3.38, 3.26,
       3.99, 3.25, 1.16, 3.41, 3.28, 3.21, 3.47, 3.44, 3.04, 3.64, 2.65,
       3.42, 2.64, 2.63, 3.1 , 3.13, 3.97, 3.71, 3.83, 3.58, 3.27, 3.43,
       3.53, 1.23, 1.06, 3.6 , 3.74, 3.45, 1.51, 2.78, 3.94, 3.05, 2.98,
       1.39, 1.58, 3.62, 3.36, 1.15, 3.98, 1.92, 2.11, 1.1 , 1.3 , 2.66,
       2.45, 2.79, 1.13, 2.49, 3.61, 3.95, 2.95, 2.8 , 2.23, 1.2 , 1.56,
       1.05, 1.19, 3.39, 3.55, 2.37, 1.21, 1.59, 2.73, 1.07, 1.41, 2.75,
       2.74, 2.61, 3.31, 2.34, 1.71, 3.06, 3.2 , 1.14, 3.32, 2.94, 2.85,
       3.48, 2.39, 2.76, 3.12, 1.87, 2.12, 2.96, 2.

In NCP we have number of main meels again it is continous but need to get converted to categporical 


In [206]:
data['CAEC'].unique()

array(['Sometimes', 'Frequently', 'Always', nan, 'Nope', 'no'],
      dtype=object)

this Column tells us about Snacking frequency again it has only 4 valid values and NOpe and No are same so need transformation.
Also this Column contains null values.

In [207]:
data['SMOKE'].unique()

array(['no', 'yes', 'Nope'], dtype=object)

In Smoking Column We have only 2 Possible values Yes and No as No and Nope are same so it also requires Transformation in the ETL Part.

In [208]:
data['CH2O'].unique()

array([2.  , 3.  , 1.  , 1.15, 1.12, 2.7 , 2.18, 2.41, 2.98, 2.44, 2.65,
       2.83, 2.85, 2.88, 2.15, 2.82, 2.59, 1.03, 1.79, 1.49, 2.07, 2.14,
       2.46, 1.53, 1.32, 1.66, 1.57, 2.84, 2.03, 1.25, 1.64, 1.3 , 1.63,
       2.1 , 1.86, 1.23, 1.05, 2.72, 2.73, 2.37, 2.67, 1.77, 2.62, 2.43,
       2.91, 2.31, 2.16, 2.89, 1.69, 1.44, 1.19, 1.02, 1.88, 1.7 , 2.04,
       1.27, 2.79, 1.43, 1.96, 1.09, 1.18, 1.98, 2.36, 2.93, 1.28, 1.39,
       1.16, 1.85, 1.33, 2.28, 2.12, 2.95, 1.11, 1.91, 1.97, 1.01, 1.6 ,
       1.84, 2.29, 2.69, 2.01, 1.95, 1.75, 2.26, 2.48, 1.04, 2.55, 2.35,
       2.57, 1.22, 1.92, 2.92, 2.24, 2.32, 1.13, 1.2 , 2.23, 2.39, 1.68,
       1.31, 1.54, 2.45, 1.99, 1.67, 2.02, 2.21, 1.36, 1.78, 1.87, 2.08,
       2.58, 2.2 , 2.54, 2.99, 1.1 , 1.06, 2.77, 1.55, 1.76, 2.49, 1.5 ,
       1.93, 1.82, 1.35, 1.83, 1.07, 2.17, 1.46, 2.8 , 2.75, 2.06, 1.59,
       2.63, 2.33, 1.17, 2.38, 1.34, 1.21, 2.5 , 2.11, 1.08, 2.05, 2.6 ,
       2.97, 2.76, 2.13, 2.22, 1.81, 1.62, 1.14, 2.

In [209]:
data['SCC'].unique()

array(['no', 'yes', 'Nope'], dtype=object)

In SCC Column We have only 2 Possible values Yes and No as No and Nope are same so it also requires Transformation in the ETL Part.

In [210]:
data['FAF'].unique()

array([0.  , 3.  , 2.  , 1.  , 0.32, 1.54, 1.98, 0.1 , 1.59, 1.4 , 1.68,
       2.21, 1.32, 0.9 , 0.6 , 0.12, 0.35, 2.54, 0.2 , 1.6 , 0.75, 0.43,
       0.55, 1.3 , 1.49, 1.23, 1.66, 0.66, 0.54, 0.82, 0.19, 1.9 , 1.07,
       1.64, 2.87, 0.62, 1.44, 0.11, 0.29, 1.93, 0.99, 1.25, 0.52, 0.28,
       2.6 , 2.24, 2.46, 0.14, 0.65, 1.52, 1.37, 0.26, 2.78, 2.35, 2.04,
       0.87, 0.63, 2.2 , 0.07, 0.03, 0.68, 2.31, 2.01, 1.26, 1.24, 0.23,
       1.84, 0.83, 1.95, 0.95, 1.97, 1.55, 1.7 , 0.48, 0.13, 0.78, 0.17,
       1.16, 2.83, 1.88, 2.51, 0.37, 2.08, 0.77, 0.79, 1.1 , 1.61, 1.19,
       0.42, 1.42, 1.35, 0.21, 0.88, 1.85, 1.56, 1.29, 0.85, 0.53, 0.25,
       1.86, 1.51, 2.11, 0.49, 1.08, 1.62, 1.22, 2.03, 2.33, 2.41, 1.94,
       1.46, 2.7 , 0.61, 2.43, 0.04, 0.51, 0.06, 1.33, 0.98, 0.46, 0.02,
       0.05, 0.7 , 2.64, 0.92, 2.29, 2.57, 2.55, 2.02, 1.91, 1.36, 2.71,
       0.24, 0.69, 0.18, 0.56, 2.89, 0.93, 0.01, 1.81, 0.73, 0.34, 0.38,
       0.44, 0.94, 1.92, 0.15, 2.16, 2.06, 2.12, 1.

THis COlumn will tells us about Water Intake and again it is numerical column we will convert it to categorical 

In [211]:
data['CALC'].unique()

array(['no', 'Sometimes', 'Frequently', 'Nope', 'Always'], dtype=object)

this Column tells us about Snacking frequency again it has only 4 valid values and NOpe and No are same so need transformation.

In [212]:
data['TUE'].unique()

array([1.000e+00, 0.000e+00, 2.000e+00, 2.950e-01, 8.390e-01, 4.790e-01,
       6.250e-01, 2.660e-01, 5.550e-01, 9.290e-01, 1.340e+00, 5.900e-01,
       1.375e+00, 1.284e+00, 6.200e-02, 9.970e-01, 7.380e-01, 8.600e-01,
       5.560e-01, 4.700e-01, 3.720e-01, 9.000e-03, 8.320e-01, 1.150e-01,
       2.560e-01, 1.547e+00, 1.906e+00, 1.639e+00, 7.150e-01, 8.290e-01,
       4.750e-01, 1.488e+00, 1.894e+00, 1.840e+00, 1.380e+00, 1.593e+00,
       1.273e+00, 2.200e-01, 3.800e-02, 1.679e+00, 8.750e-01, 1.010e+00,
       1.530e-01, 6.360e-01, 1.120e+00, 9.700e-02, 1.366e+00, 7.200e-01,
       3.220e-01, 9.400e-01, 4.560e-01, 1.164e+00, 3.310e-01, 1.330e-01,
       1.594e+00, 1.329e+00, 1.674e+00, 4.660e-01, 9.310e-01, 7.450e-01,
       1.708e+00, 1.616e+00, 1.242e+00, 2.770e-01, 1.960e-01, 7.100e-02,
       8.150e-01, 3.690e-01, 9.300e-01, 1.467e+00, 1.163e+00, 3.270e-01,
       7.050e-01, 3.710e-01, 5.600e-01, 1.526e+00, 1.683e+00, 1.290e-01,
       1.884e+00, 9.080e-01, 1.743e+00, 1.895e+00, 

This Column will telss us about time spend on screen daily on the scale of 0 to 3 so it also required mapping

In [213]:
data['MTRANS'].unique()

array(['Public_Transportation', 'Walking', 'Automobile', 'Motorbike',
       'Bike', nan], dtype=object)

This COlumn have Null Values. and again Motorbike and Bike are Same so we need to use only on evalue

In [214]:
data['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'normal_Weight', 'Insufficient_Weight',
       'Obesity_Type_II', 'Obesity_Type_III'], dtype=object)

## Data Transformation

Let's Make Id column as Index


In [215]:
data.set_index('Id', inplace=True)
data

Gender  Age  Height  Weight family_history_with_overweight  \
Id                                                                           
Person_01       Female   21    1.62   64.00                            yes   
Person_02       Female   21    1.52   56.00                            yes   
Person_03         Male   23    1.80   77.00                            yes   
Person_04         Male   27    1.80   87.00                             no   
Person_05         Male   22    1.78   89.80                             no   
...                ...  ...     ...     ...                            ...   
Person_10306      Male   26    1.84   96.19                            yes   
Person_10307      Male   23    1.82   93.09                            yes   
Person_10308      Male   23    1.72   85.31                            yes   
Person_10309      Male   23    1.79   90.00                            yes   
Person_10310  LGBTQAB+   25    1.70   80.75                            yes   

             FAVC  FCVC   NCP       CAEC SMOKE  CH2O  SCC   FAF    TUE  \
Id                                                                       
Person_01      no  2.00  3.00  Sometimes    no  2.00   no  0.00  1.000   
Person_02      no  3.00  3.00  Sometimes   yes  3.00  yes  3.00  0.000   
Person_03      no  2.00  3.00  Sometimes    no  2.00   no  2.00  1.000   
Person_04      no  3.00  3.00  Sometimes    no  2.00   no  2.00  0.000   
Person_05      no  2.00  1.00  Sometimes    no  2.00   no  0.00  0.000   
...           ...   ...   ...        ...   ...   ...  ...   ...    ...   
Person_10306  yes  1.32  2.28  Sometimes    no  2.00   no  1.81  1.940   
Person_10307  yes  1.88  1.24  Sometimes    no  2.00   no  0.00  1.541   
Person_10308  yes  2.95  3.00  Sometimes    no  2.97   no  0.00  0.947   
Person_10309  yes  2.07  3.00  Sometimes    no  1.08   no  0.00  1.922   
Person_10310  yes  2.55  3.00  Sometimes    no  2.27   no  0.50  1.000   

                    CALC                 MTRANS           NObeyesdad  
Id                                                                    
Person_01             no  Public_Transportation        Normal_Weight  
Person_02      Sometimes  Public_Transportation        Normal_Weight  
Person_03     Frequently  Public_Transportation        Normal_Weight  
Person_04     Frequently                Walking   Overweight_Level_I  
Person_05      Sometimes  Public_Transportation  Overweight_Level_II  
...                  ...                    ...                  ...  
Person_10306   Sometimes  Public_Transportation  Overweight_Level_II  
Person_10307   Sometimes  Public_Transportation  Overweight_Level_II  
Person_10308   Sometimes  Public_Transportation  Overweight_Level_II  
Person_10309   Sometimes  Public_Transportation  Overweight_Level_II  
Person_10310  Frequently  Public_Transportation  Overweight_Level_II  

[10310 rows x 17 columns]

for Gender column let's convert male to Male

In [216]:
data['Gender'] = data['Gender'].replace("male", "Male")

In [217]:
data['Gender'].unique()

array(['Female', 'Male', 'LGBTQAB+'], dtype=object)

for FAVC column we need to convert nope to no

In [218]:
data['FAVC'] = np.where(data['FAVC'] == "Nope", "no", data['FAVC'])

data['FAVC'].unique()

array(['no', 'yes'], dtype=object)

For Family_history column we need to convert nope to no

In [219]:
data['family_history_with_overweight'] = data['family_history_with_overweight'].replace("Nope", "no")

data['family_history_with_overweight'].unique()

array(['yes', 'no'], dtype=object)

For Smoke and CAEC Column we again need to convert no to nope

In [220]:
data['CAEC'] = np.where(data["CAEC"] == "no", "Nope", data['CAEC'])

data['SMOKE'] = np.where(data["SMOKE"] == "no", "Nope", data['SMOKE'])

In [221]:
data['CAEC'].unique()



array(['Sometimes', 'Frequently', 'Always', nan, 'Nope'], dtype=object)

In [222]:
data['SMOKE'].unique()

array(['Nope', 'yes'], dtype=object)

For FCVC column (frequency of vegetable consumption) we need to have a data on Scale of 1 to 3 but we have continous data as it may appear hard for user to give input in that way so grouped these values in 1,2 and 3 

In [223]:
my.minmax(data['FCVC'])

The Minimum Value in this column is going to be 1.0
The Maximum Value in this column is going to be 3.0


In [224]:
data['FCVC'] = data['FCVC'].apply(lambda x : 1 if x <= 1 else 2 if x <= 2 and x > 1 else 3)

In [225]:
data['FCVC'].unique()

array([2, 3, 1], dtype=int64)

For NCP COlumn i.e, number of Main Meals Perday we need again a scaled data not in a continous type as it is not user friendly 

In [226]:
my.minmax(data['NCP'])

The Minimum Value in this column is going to be 1.0
The Maximum Value in this column is going to be 4.0


In [227]:
data['NCP'] = data['NCP'].apply(lambda x : 1 if x <= 1 else 2 if x <= 2 and x > 1 else 3 if x <= 3 and x > 2 else 4)

data['NCP'].unique()

array([3, 1, 4, 2], dtype=int64)

For CH2O column i.e, Concumption of water daily basis again a continous COlumn and we need to make it categorical and user friendly input

In [228]:
my.minmax(data['CH2O'])

The Minimum Value in this column is going to be 1.0
The Maximum Value in this column is going to be 3.0


In [229]:
data['CH2O'] = data['CH2O'].apply(lambda x : 1 if x <= 1 else 2 if x <= 2 and x > 1 else 3 )

data['CH2O'].unique()

array([2, 3, 1], dtype=int64)

For SCC Column we need to transform Nope values to no 

In [230]:
data['SCC'] = np.where(data['SCC'] == 'Nope', "no", data['SCC'])

In [231]:
data['SCC'].unique()

array(['no', 'yes'], dtype=object)

For FAF column i.e, Frequency of Physical Activity we need to have a scaled data so we are going to transform the data from continous nature to categorical Nature as it is always more user friendly

In [232]:
my.minmax(data['FAF'])

The Minimum Value in this column is going to be 0.0
The Maximum Value in this column is going to be 3.0


In [233]:
data['FAF'] = data['FAF'].apply(lambda x : 0 if x <= 0 else 1 if x > 0  and x <= 1 else 2 if x <= 2 and x > 1 else 3)

data['FAF'].unique()


array([0, 3, 2, 1], dtype=int64)

for column name TUE that tells us about time spent on techinology so for that matter we need to categorise it let's look at the values so that we will categorise into low , high and medium usage 

In [234]:
my.minmax(data['TUE'])

The Minimum Value in this column is going to be 0.0
The Maximum Value in this column is going to be 2.0


In [235]:
data['TUE'] = data['TUE'].apply(lambda x : "Low Usage" if 0 <= x <= 0.7 else "Moderate Usage" if 0.7 < x <= 1.4 else "High Usage")

data['TUE'].unique()

array(['Moderate Usage', 'Low Usage', 'High Usage'], dtype=object)

#### NOW FOR FURTHER TRANSFORMATION OF 3 COLUMNS (MTRANS, CALC AND NOBEYESDAD) WE WILL USE SQL QUERIES 

#### For that matter let's establish a connection between SQL and Python so that we can write queries here itself

## Data Loading

In [236]:
import pymysql

pipeline = pymysql.connect(
    host= "localhost",
    user = "root",
    password= "14072003"
)

    
etl = pipeline.cursor()

In [237]:
etl.execute("Drop database if exists obesity;")

1

In [238]:
etl.execute("Create Database Obesity;")
print("Database Created Succcessfully")

Database Created Succcessfully


In [239]:
from sqlalchemy import create_engine, text

In [240]:
!pip install mysql-connector-python

In [241]:
connector = create_engine("mysql+mysqlconnector://root:14072003@localhost:3306/Obesity")
print("Connection Set Up Successfully")

Connection Set Up Successfully


NOW LET'S PUSH ALL THE DATA IN SQL DATABASE


In [242]:
data.to_sql(
    name="Obesity_Data",
    con = connector,
    if_exists="replace",
    index=False
)

print("WHOLE DATA IS PUSHED INTO THE SQL DATABASE")

WHOLE DATA IS PUSHED INTO THE SQL DATABASE


In [243]:
pd.read_sql_query("Select * from Obesity_data;", connector)

Gender  Age  Height  Weight family_history_with_overweight FAVC  \
0        Female   21    1.62   64.00                            yes   no   
1        Female   21    1.52   56.00                            yes   no   
2          Male   23    1.80   77.00                            yes   no   
3          Male   27    1.80   87.00                             no   no   
4          Male   22    1.78   89.80                             no   no   
...         ...  ...     ...     ...                            ...  ...   
10305      Male   26    1.84   96.19                            yes  yes   
10306      Male   23    1.82   93.09                            yes  yes   
10307      Male   23    1.72   85.31                            yes  yes   
10308      Male   23    1.79   90.00                            yes  yes   
10309  LGBTQAB+   25    1.70   80.75                            yes  yes   

       FCVC  NCP       CAEC SMOKE  CH2O  SCC  FAF             TUE        CALC  \
0         2    3  Sometimes  Nope     2   no    0  Moderate Usage          no   
1         3    3  Sometimes   yes     3  yes    3       Low Usage   Sometimes   
2         2    3  Sometimes  Nope     2   no    2  Moderate Usage  Frequently   
3         3    3  Sometimes  Nope     2   no    2       Low Usage  Frequently   
4         2    1  Sometimes  Nope     2   no    0       Low Usage   Sometimes   
...     ...  ...        ...   ...   ...  ...  ...             ...         ...   
10305     2    3  Sometimes  Nope     2   no    2      High Usage   Sometimes   
10306     2    2  Sometimes  Nope     2   no    0      High Usage   Sometimes   
10307     3    3  Sometimes  Nope     3   no    0  Moderate Usage   Sometimes   
10308     3    3  Sometimes  Nope     2   no    0      High Usage   Sometimes   
10309     3    3  Sometimes  Nope     3   no    1  Moderate Usage  Frequently   

                      MTRANS           NObeyesdad  
0      Public_Transportation        Normal_Weight  
1      Public_Transportation        Normal_Weight  
2      Public_Transportation        Normal_Weight  
3                    Walking   Overweight_Level_I  
4      Public_Transportation  Overweight_Level_II  
...                      ...                  ...  
10305  Public_Transportation  Overweight_Level_II  
10306  Public_Transportation  Overweight_Level_II  
10307  Public_Transportation  Overweight_Level_II  
10308  Public_Transportation  Overweight_Level_II  
10309  Public_Transportation  Overweight_Level_II  

[10310 rows x 17 columns]

##### For MTrans data 

In [244]:
pd.read_sql_query("Select distinct mtrans from obesity_data;", connector)

mtrans
0  Public_Transportation
1                Walking
2             Automobile
3              Motorbike
4                   Bike
5                   None

Lets merge motorbike and bike values into one

In [245]:
with connector.begin() as conn:
    conn.execute(text(
        "UPDATE Obesity_data SET MTrans = 'Bike' WHERE MTrans = 'MotorBike'"
    ))

pd.read_sql_query("Select distinct mtrans from obesity_data;", connector)

mtrans
0  Public_Transportation
1                Walking
2             Automobile
3                   Bike
4                   None

##### For CalC data

In [246]:
pd.read_sql_query("Select distinct calc from obesity_data;", connector)

calc
0          no
1   Sometimes
2  Frequently
3        Nope
4      Always

Here we need to merge no and Nope values and put Never instead of both

In [247]:
with connector.begin() as conn:
    conn.execute(text(
        "Update obesity_data set calc = 'Never' where calc in ('no', 'never')"))
    
pd.read_sql_query("Select distinct calc from obesity_data;", connector)

calc
0       Never
1   Sometimes
2  Frequently
3        Nope
4      Always

##### For NObeyesdad

In [248]:
pd.read_sql_query("Select Distinct nobeyesdad from obesity_data", connector)

nobeyesdad
0        Normal_Weight
1   Overweight_Level_I
2  Overweight_Level_II
3       Obesity_Type_I
4  Insufficient_Weight
5      Obesity_Type_II
6     Obesity_Type_III

In [249]:

with connector.begin() as con:
    con.execute(text("""
        UPDATE obesity_data
        SET nobeyesdad = CASE
            WHEN nobeyesdad = 'Normal_Weight' THEN 'Healthy'
            WHEN nobeyesdad = 'Insufficient_Weight' THEN 'Underweight'
            WHEN nobeyesdad IN ('Overweight_Level_I', 'Overweight_Level_II') THEN 'Overweight'
            WHEN nobeyesdad IN ('Obesity_Type_I', 'Obesity_Type_II') THEN 'Obese'
            WHEN nobeyesdad = 'Obesity_Type_III' THEN 'Severely Obese'
            ELSE nobeyesdad
        END
    """))


In [250]:
pd.read_sql_query("Select distinct nobeyesdad from obesity_data", connector)

nobeyesdad
0         Healthy
1      Overweight
2           Obese
3     Underweight
4  Severely Obese

## Changing Column Names 

lets refine columns name as well as we have ncp so we will change it to no_of_meals and so on using sql commands 

##### FCVC to Freq_of_Vegie_Consump

In [251]:
with connector.begin() as conn:
    conn.execute(text(
        "ALter Table obesity_data RENAME column FCVC to Freq_of_Vegie_Consump "
    ))

pd.read_sql_query("Select * from Obesity_data", connector)

Gender  Age  Height  Weight family_history_with_overweight FAVC  \
0        Female   21    1.62   64.00                            yes   no   
1        Female   21    1.52   56.00                            yes   no   
2          Male   23    1.80   77.00                            yes   no   
3          Male   27    1.80   87.00                             no   no   
4          Male   22    1.78   89.80                             no   no   
...         ...  ...     ...     ...                            ...  ...   
10305      Male   26    1.84   96.19                            yes  yes   
10306      Male   23    1.82   93.09                            yes  yes   
10307      Male   23    1.72   85.31                            yes  yes   
10308      Male   23    1.79   90.00                            yes  yes   
10309  LGBTQAB+   25    1.70   80.75                            yes  yes   

       Freq_of_Vegie_Consump  NCP       CAEC SMOKE  CH2O  SCC  FAF  \
0                          2    3  Sometimes  Nope     2   no    0   
1                          3    3  Sometimes   yes     3  yes    3   
2                          2    3  Sometimes  Nope     2   no    2   
3                          3    3  Sometimes  Nope     2   no    2   
4                          2    1  Sometimes  Nope     2   no    0   
...                      ...  ...        ...   ...   ...  ...  ...   
10305                      2    3  Sometimes  Nope     2   no    2   
10306                      2    2  Sometimes  Nope     2   no    0   
10307                      3    3  Sometimes  Nope     3   no    0   
10308                      3    3  Sometimes  Nope     2   no    0   
10309                      3    3  Sometimes  Nope     3   no    1   

                  TUE        CALC                 MTRANS  NObeyesdad  
0      Moderate Usage       Never  Public_Transportation     Healthy  
1           Low Usage   Sometimes  Public_Transportation     Healthy  
2      Moderate Usage  Frequently  Public_Transportation     Healthy  
3           Low Usage  Frequently                Walking  Overweight  
4           Low Usage   Sometimes  Public_Transportation  Overweight  
...               ...         ...                    ...         ...  
10305      High Usage   Sometimes  Public_Transportation  Overweight  
10306      High Usage   Sometimes  Public_Transportation  Overweight  
10307  Moderate Usage   Sometimes  Public_Transportation  Overweight  
10308      High Usage   Sometimes  Public_Transportation  Overweight  
10309  Moderate Usage  Frequently  Public_Transportation  Overweight  

[10310 rows x 17 columns]

##### FAVC to Fried_Food_Consump

In [252]:
with connector.begin() as conn:
    conn.execute(text(
        "ALter Table obesity_data RENAME column FAVC to Fried_Food_Consump "
    ))

pd.read_sql_query("Select * from Obesity_data", connector)

Gender  Age  Height  Weight family_history_with_overweight  \
0        Female   21    1.62   64.00                            yes   
1        Female   21    1.52   56.00                            yes   
2          Male   23    1.80   77.00                            yes   
3          Male   27    1.80   87.00                             no   
4          Male   22    1.78   89.80                             no   
...         ...  ...     ...     ...                            ...   
10305      Male   26    1.84   96.19                            yes   
10306      Male   23    1.82   93.09                            yes   
10307      Male   23    1.72   85.31                            yes   
10308      Male   23    1.79   90.00                            yes   
10309  LGBTQAB+   25    1.70   80.75                            yes   

      Fried_Food_Consump  Freq_of_Vegie_Consump  NCP       CAEC SMOKE  CH2O  \
0                     no                      2    3  Sometimes  Nope     2   
1                     no                      3    3  Sometimes   yes     3   
2                     no                      2    3  Sometimes  Nope     2   
3                     no                      3    3  Sometimes  Nope     2   
4                     no                      2    1  Sometimes  Nope     2   
...                  ...                    ...  ...        ...   ...   ...   
10305                yes                      2    3  Sometimes  Nope     2   
10306                yes                      2    2  Sometimes  Nope     2   
10307                yes                      3    3  Sometimes  Nope     3   
10308                yes                      3    3  Sometimes  Nope     2   
10309                yes                      3    3  Sometimes  Nope     3   

       SCC  FAF             TUE        CALC                 MTRANS  NObeyesdad  
0       no    0  Moderate Usage       Never  Public_Transportation     Healthy  
1      yes    3       Low Usage   Sometimes  Public_Transportation     Healthy  
2       no    2  Moderate Usage  Frequently  Public_Transportation     Healthy  
3       no    2       Low Usage  Frequently                Walking  Overweight  
4       no    0       Low Usage   Sometimes  Public_Transportation  Overweight  
...    ...  ...             ...         ...                    ...         ...  
10305   no    2      High Usage   Sometimes  Public_Transportation  Overweight  
10306   no    0      High Usage   Sometimes  Public_Transportation  Overweight  
10307   no    0  Moderate Usage   Sometimes  Public_Transportation  Overweight  
10308   no    0      High Usage   Sometimes  Public_Transportation  Overweight  
10309   no    1  Moderate Usage  Frequently  Public_Transportation  Overweight  

[10310 rows x 17 columns]

- LET'S DO FOR OTHER COLUMNS AS WELL AND HERE IS THE QUICK SUMMARY OF WHAT WE WANNA DO

    - NCP TO NO_OF_MEALS
    - CAEC TO SNACKING_FREQ
    - CH20 TO WATER_CONSUMPTION
    - SCC TO CALORIE_MONITORING
    - FAF TO PHYSICAL_ACTIVITY
    - TUE TO TIME_SPEND_ON_TECH 
    - CALC TO ALCOHOL_CONSUMP
    - NOBEYESDAD TO HEALTH_CONDITION


In [253]:
with connector.begin() as con:
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN NCP TO no_of_meals"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN CAEC TO snacking_freq"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN CH2O TO water_consumption"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN SCC TO calorie_monitoring"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN FAF TO physical_activity"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN TUE TO time_spend_on_tech"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN CALC TO alcohol_consump"))
    con.execute(text("ALTER TABLE obesity_data RENAME COLUMN NObeyesdad TO health_condition"))



pd.read_sql_query("Show Columns from obesity_data", connector)


Field    Type Null Key Default Extra
0                           Gender    text  YES        None      
1                              Age  bigint  YES        None      
2                           Height  double  YES        None      
3                           Weight  double  YES        None      
4   family_history_with_overweight    text  YES        None      
5               Fried_Food_Consump    text  YES        None      
6            Freq_of_Vegie_Consump  bigint  YES        None      
7                      no_of_meals  bigint  YES        None      
8                    snacking_freq    text  YES        None      
9                            SMOKE    text  YES        None      
10               water_consumption  bigint  YES        None      
11              calorie_monitoring    text  YES        None      
12               physical_activity  bigint  YES        None      
13              time_spend_on_tech    text  YES        None      
14                 alcohol_consump    text  YES        None      
15                          MTRANS    text  YES        None      
16                health_condition    text  YES        None

## Data Loading 2.0

AS FOR FURTHER MODELLING WE NEED THIS DATA ON PYTHON SO LET'S MAKE A DATFRAME AND SAVE IT THERE |

In [254]:
df = pd.read_sql_query("Select * from obesity_data", connector)

df.head()

Gender  Age  Height  Weight family_history_with_overweight  \
0  Female   21    1.62    64.0                            yes   
1  Female   21    1.52    56.0                            yes   
2    Male   23    1.80    77.0                            yes   
3    Male   27    1.80    87.0                             no   
4    Male   22    1.78    89.8                             no   

  Fried_Food_Consump  Freq_of_Vegie_Consump  no_of_meals snacking_freq SMOKE  \
0                 no                      2            3     Sometimes  Nope   
1                 no                      3            3     Sometimes   yes   
2                 no                      2            3     Sometimes  Nope   
3                 no                      3            3     Sometimes  Nope   
4                 no                      2            1     Sometimes  Nope   

   water_consumption calorie_monitoring  physical_activity time_spend_on_tech  \
0                  2                 no                  0     Moderate Usage   
1                  3                yes                  3          Low Usage   
2                  2                 no                  2     Moderate Usage   
3                  2                 no                  2          Low Usage   
4                  2                 no                  0          Low Usage   

  alcohol_consump                 MTRANS health_condition  
0           Never  Public_Transportation          Healthy  
1       Sometimes  Public_Transportation          Healthy  
2      Frequently  Public_Transportation          Healthy  
3      Frequently                Walking       Overweight  
4       Sometimes  Public_Transportation       Overweight

In [255]:
df.shape

(10310, 17)